#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Where this plugin keeps its own things. Not a function: every other file in
# here reads these, so they are set once, first.
#
# The libraries sit at <plugin>/hooks/lib, so the plugin's own directory is two
# above them wherever the install put it. One fork, not three: a hook may be run
# by a relative path, so the directory is resolved once.
# Every other file in lib/ reads these. One function to a file means no file
# can see its own variables being used, so they read as unused here.
# shellcheck disable=SC2034
PLUGIN_LIB="$(cd "${BASH_SOURCE[0]%/*}/.." && pwd)"
PLUGIN_ROOT="${PLUGIN_LIB%/*/*}"

# The build writes this from the plugin's manifest. It is the only thing in lib/
# that knows a plugin's name.
. "$PLUGIN_LIB/plugin-manifest.sh"

plugin_named_home="${PLUGIN_PREFIX}_HOME"
PLUGIN_HOME="${!plugin_named_home:-$HOME/.$PLUGIN_NAME}"
PLUGIN_SETTINGS="$PLUGIN_HOME/settings"
PLUGIN_STATE="$PLUGIN_HOME/state"
