#!/usr/bin/env bash
# Generated by ./build. Edit the sources at the repository root instead.

cat >/dev/null

. "$(dirname "$0")/hook-settings-lib.sh"

apply_migrations

notice="$UNSOLICITED_TEXT_STATE/new-version"
checked="$UNSOLICITED_TEXT_STATE/version-checked"

installed="$(installed_version)" || installed=""

newer_than_installed() {
  [ -n "$installed" ] || return 1
  [ "$1" = "$installed" ] && return 1
  [ "$(printf '%s\n%s\n' "$installed" "$1" | sort --version-sort | tail -1)" = "$1" ]
}

# A notice written before an update names a version this copy has already
# passed, so it goes without being said.
if [ -f "$notice" ]; then
  waiting="$(cat "$notice")"
  rm -f "$notice"
  if newer_than_installed "$waiting"; then
    said="[unsolicited-text] version $waiting is now available (current: $installed). Update with unsolicited-text:update, or stop being told with unsolicited-text:settings"
    # systemMessage reaches the user; the context reaches the agent either way.
    printf '{"systemMessage":"%s","hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":"%s"}}\n' \
      "$said" "$said"
  fi
fi

update_check || exit 0
command -v curl >/dev/null 2>&1 || exit 0

interval="$(( $(counted "$(setting_value UNSOLICITED_TEXT_UPDATE_CHECK_DAYS 1)" 1) * 86400 ))"
now="$(date +%s)"
[ -f "$checked" ] && [ "$((now - $(cat "$checked")))" -lt "$interval" ] && exit 0

[ -n "$installed" ] || exit 0

published="$(setting_value UNSOLICITED_TEXT_VERSION_SOURCE \
  https://raw.githubusercontent.com/justinkek/unsolicited-text/main/package.json)"

mkdir -p "$UNSOLICITED_TEXT_STATE"
printf '%s' "$now" > "$checked"

(
  # A version is digits, dots and dashes. Anything else is not read, so nothing
  # a published file says can end up inside the JSON this hook prints.
  latest="$(curl --silent --fail --max-time 5 "$published" 2>/dev/null \
    | sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([0-9A-Za-z.+-]*\)".*/\1/p' | head -1)"
  [ -n "$latest" ] || exit 0
  newer_than_installed "$latest" || exit 0
  # The notice holds the version, and the sentence is written when it is said,
  # against whatever is installed by then.
  printf '%s' "$latest" > "$notice"
) >/dev/null 2>&1 &

exit 0
