#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Some clients never carry what the session start hooks print into the session,
# and some run no session start hook at all. On those, the print arrives on the
# first prompt instead, once.
payload="$(cat)"

. "$(dirname "$0")/lib/payload.sh"
. "$(dirname "$0")/lib/state.sh"
. "$(dirname "$0")/lib/say.sh"

session_id="$(hook_field "$payload" session_id)"
[ -n "$session_id" ] || exit 0

# Marked means the session start hooks already ran and were heard.
plugin_marked "session-start/$session_id" && exit 0
plugin_mark "session-start/$session_id"

# Each script is asked for its text rather than its envelope, because what all
# of them print is wrapped once, as the answer to this event.
for script in $(plugin_session_start_hooks); do
  [ -f "$(dirname "$0")/$script" ] || continue
  printf '%s' "$payload" | env "${PLUGIN_PREFIX}_PLAIN=1" bash "$(dirname "$0")/$script"
done | hook_say UserPromptSubmit
exit 0
