#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# The event a hook was called for, out of the payload it was handed.
hook_event_of() { hook_field "$1" hook_event_name; }
