#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# The nearest .<plugin>/settings at or above the project, so a hook run in a
# subdirectory reads what the project root holds. The home directory is where
# the person's own file sits, so the search stops short of it: that file is
# never read as a project's.
project_settings_file() {
  local directory="$PLUGIN_PROJECT"
  while [ -n "$directory" ] && [ "$directory" != "$HOME" ]; do
    if [ -f "$directory/.$PLUGIN_NAME/settings" ]; then
      printf '%s' "$directory/.$PLUGIN_NAME/settings"
      return 0
    fi
    [ "$directory" = "/" ] && break
    directory="$(dirname "$directory")"
  done
  return 1
}
