#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# A setting is named without its prefix here, and carries it everywhere a
# person writes it: in the file, in the environment, and in the settings skill.
setting_value() {
  local key="$1" named="${PLUGIN_PREFIX}_$1" value default
  default="$(plugin_expanded "$(plugin_setting_default "$key")")"

  value="${!named-}"
  [ -n "$value" ] || value="$(settings_file_value "$named")"
  [ -n "$value" ] || { printf '%s' "$default"; return 0; }

  if [ "$(plugin_setting_kind "$key")" = "switch" ]; then
    value="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
  fi

  if plugin_setting_holds "$key" "$value"; then
    plugin_expanded "$value"
  else
    printf '%s' "$default"
  fi
}
