#!/usr/bin/env bash

REPOSITORY="$(cd "$(dirname "$0")/.." && pwd)"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

pass=0
fail=0

assert() {
  local label="$1" outcome="$2" detail="$3"
  if [ "$outcome" = "0" ]; then
    printf "  PASS  %s\n" "$label"
    pass=$((pass + 1))
  else
    printf "  FAIL  %s — %s\n" "$label" "$detail"
    fail=$((fail + 1))
  fi
}

printf "Test group: what ships is what the sources build\n"

"$REPOSITORY/build" "$TMPDIR/dist" >/dev/null
assert "the build runs" "$?" "nothing can be shipped from these sources"

diff --recursive --unified "$REPOSITORY/dist" "$TMPDIR/dist" > "$TMPDIR/drift"
assert "and dist matches it" "$?" \
  "an install would copy something no source says - run ./build"

printf "\nTest group: every folder holds what it declares, and nothing else\n"

PRODUCTS="$REPOSITORY/products.json"

ships() { jq --exit-status --arg product "$1" --arg part "$2" '.[$product].ships | index($part)' "$PRODUCTS" >/dev/null; }

declared() { jq --raw-output 'keys[]' "$PRODUCTS"; }

for product in $(declared); do
  for part in hooks rules skills commands; do
    case "$part" in
      hooks) file="hooks/load-rules.sh" ;;
      rules) file="rules/reply-shape.md" ;;
      skills) file="skills/reload/SKILL.md" ;;
      commands) file="commands/reload.md" ;;
    esac

    if ships "$product" "$part"; then
      [ -e "$REPOSITORY/dist/$product/$file" ]
      assert "$product ships $part" "$?" "it declares $part and an install from that folder is missing it"
    else
      [ ! -e "$REPOSITORY/dist/$product/$part" ]
      assert "$product ships no $part" "$?" \
        "it declares none and the folder holds $part anyway, so an install copies what nothing there reads"
    fi
  done
done

for product in $(declared); do
  [ -d "$REPOSITORY/dist/$product" ]
  assert "$product has a folder" "$?" "products names it and the build writes nothing"
done

for folder in "$REPOSITORY"/dist/*/; do
  named="$(basename "$folder")"
  declared | grep --quiet --line-regexp "$named"
  assert "$named is declared in products.json" "$?" "the build writes a folder nothing says belongs there"
done

for product in claude-code claude-cloud codex pi chat-cowork; do
  grep --quiet --fixed-strings 'Installing' "$REPOSITORY/dist/$product/README.md"
  assert "$product says how it is installed" "$?" "the folder is there and nothing tells a reader what to do with it"
done

printf "\nTest group: a generated file says so\n"

for generated in "$REPOSITORY"/dist/*/README.md "$REPOSITORY"/dist/*/hooks/load-rules.sh \
  "$REPOSITORY"/skills/*/SKILL.md; do
  grep --quiet --fixed-strings 'Generated by' "$generated"
  assert "${generated#$REPOSITORY/} says it is generated" "$?" \
    "a reader edits it, runs the build, and loses the edit"
done

printf "\n%d passed, %d failed\n" "$pass" "$fail"
[ "$fail" -eq 0 ]
