#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Every hook enters through here. A shell too old to run these libraries says so
# now, in one sentence, rather than part of the way through a hook with a syntax
# error a person has to read backwards from.
#
# 3.2 is the floor because that is what the libraries use: ${BASH_SOURCE[0]},
# ${value//a/b} and ${!name}. Nothing here needs bash 4, and 3.2 is what a Mac
# ships as /bin/bash.

if [ -z "${PLUGIN_SHELL_CHECKED-}" ]; then
  PLUGIN_SHELL_CHECKED=1
  if [ -z "${BASH_VERSINFO-}" ] \
    || [ "${BASH_VERSINFO[0]}" -lt 3 ] \
    || { [ "${BASH_VERSINFO[0]}" -eq 3 ] && [ "${BASH_VERSINFO[1]}" -lt 2 ]; }
  then
    printf 'this plugin needs bash 3.2 or newer, and this is %s\n' \
      "${BASH_VERSION:-not bash}" >&2
    exit 1
  fi
fi
