#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# The entries in the tool call a hook was handed, that the hook's `on` list asks
# for, one JSON object to a line. Each has the same fields on every client:
#
#   {"kind":"edit","tool":"Edit","file":"run.sh","command":"","added":"enc=1",
#    "removed":"value=1","pattern":"","url":"","query":"","prompt":""}
#
# One call can be several entries: a Codex patch touching three files is three.
tool_entries() {
  local payload="$1" entry kind subject
  command -v tool_entries_read >/dev/null 2>&1 || return 0
  while IFS= read -r entry; do
    [ -n "$entry" ] || continue
    kind="$(jq --raw-output '.kind' <<< "$entry")"
    subject="$(jq --raw-output '
      if .kind == "bash" or .kind == "powershell" then .command
      elif .kind == "grep" or .kind == "glob" then .pattern
      elif .kind == "web_fetch" then .url
      elif .kind == "web_search" then .query
      elif .kind == "agent" then .prompt
      elif .kind == "mcp" or .kind == "other" then .tool
      else .file end' <<< "$entry")"
    tool_wanted "$kind" "$subject" && printf '%s\n' "$entry"
  done < <(tool_entries_read "$payload")
}
