#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Asks now and then whether a newer copy of this plugin has been published, and
# says so on the next prompt. The asking happens in the background, so nothing
# here waits on the network.
cat >/dev/null

. "$(dirname "$0")/lib/state.sh"

notice="$PLUGIN_STATE/new-version"
checked="$PLUGIN_STATE/version-checked"

installed="$(installed_version)" || installed=""

newer_than_installed() {
  [ -n "$installed" ] || return 1
  [ "$1" = "$installed" ] && return 1
  [ "$(printf '%s\n%s\n' "$installed" "$1" | sort --version-sort | tail -1)" = "$1" ]
}

# A notice written before an update names a version this copy has already
# passed, so it goes without being said.
if [ -f "$notice" ]; then
  waiting="$(cat "$notice")"
  rm -f "$notice"
  if newer_than_installed "$waiting"; then
    said="[$PLUGIN_NAME] version $waiting is now available (current: $installed). Update with $PLUGIN_NAME:update, or stop being told with $PLUGIN_NAME:settings"
    # systemMessage reaches the user; the context reaches the agent either way.
    printf '{"systemMessage":"%s","hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":"%s"}}\n' \
      "$said" "$said"
  fi
fi

setting_on UPDATE_CHECK || exit 0
command -v curl >/dev/null 2>&1 || exit 0

interval="$(( $(setting_value UPDATE_CHECK_DAYS) * 86400 ))"
now="$(date +%s)"
[ -f "$checked" ] && [ "$((now - $(cat "$checked")))" -lt "$interval" ] && exit 0

[ -n "$installed" ] || exit 0

published="$(setting_value VERSION_SOURCE)"
[ -n "$published" ] || exit 0

mkdir -p "$PLUGIN_STATE"
printf '%s' "$now" > "$checked"

(
  # A version is digits, dots and dashes. Anything else is not read, so nothing
  # a published file says can end up inside the JSON this hook prints.
  latest="$(curl --silent --fail --max-time 5 "$published" 2>/dev/null \
    | sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([0-9A-Za-z.+-]*\)".*/\1/p' | head -1)"
  [ -n "$latest" ] || exit 0
  newer_than_installed "$latest" || exit 0
  # The notice holds the version, and the sentence is written when it is said,
  # against whatever is installed by then.
  printf '%s' "$latest" > "$notice"
) >/dev/null 2>&1 &

exit 0
