#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

input="$(cat)"

command -v jq >/dev/null 2>&1 || exit 0

. "$(dirname "$0")/lib/payload.sh"

[ "$(hook_field "$input" stop_hook_active)" = "true" ] && exit 0

transcript="$(hook_field "$input" transcript_path)"

session_id="$(hook_field "$input" session_id)"
[ -n "$session_id" ] || exit 0

. "$(dirname "$0")/lib/reply.sh"
. "$(dirname "$0")/lib/notes.sh"
. "$(dirname "$0")/lib/settings-lib.sh"

last="$(hook_last_reply "$input" "$transcript")"
[ -n "$last" ] || exit 0

line_ceiling="$(prose_line_ceiling)"
word_ceiling="$(prose_word_ceiling)"

fence="$(printf '\140\140\140')"
queue_tag="$(printf '\140[queue]\140')"
drawn="─ │ ┌ ┐ └ ┘ ├ ┤ ┬ ┴ ┼ ► ◄ ▲ ▼ → ← ↑ ↓"
counted="$(printf '%s\n' "$last" | awk -v fence="$fence" -v queue_tag="$queue_tag" -v drawn="$drawn" '
  BEGIN { marks = split(drawn, mark, " ") }
  function drawing(line,   i) {
    for (i = 1; i <= marks; i++) if (index(line, mark[i])) return 1
    return 0
  }
  { probe = $0; sub(/^[[:space:]]+/, "", probe) }
  !seen && probe ~ /[[:alnum:]]/ { seen = 1; if (index(probe, " › ")) next }
  index(probe, fence) == 1 { fenced = !fenced; next }
  fenced { next }
  probe == queue_tag { queued = 1; next }
  queued && probe ~ /^[0-9]+\. / { next }
  queued && probe != "" { queued = 0 }
  index(probe, "|") == 1 { next }
  drawing(probe) { next }
  probe ~ /[[:alnum:]]/ { prose_lines++; prose_words += NF }
  END { print prose_lines + 0, prose_words + 0 }')"
prose_lines="${counted% *}"
prose_words="${counted#* }"

# One over a ceiling of nothing is one line, not "1 lines".
if [ "$prose_lines" -gt "$line_ceiling" ]; then
  if [ "$prose_lines" = "1" ]; then counted_word="line"; else counted_word="lines"; fi
  ran="$prose_lines $counted_word of prose against a ceiling of $line_ceiling"
elif [ "$prose_words" -gt "$word_ceiling" ]; then
  if [ "$prose_words" = "1" ]; then counted_word="word"; else counted_word="words"; fi
  ran="$prose_words $counted_word of prose against a ceiling of $word_ceiling"
else
  exit 0
fi

stop_note_record "$session_id" "[reply-shape] The last reply ran $ran. Hold this one to the ceiling: send only what the reader needs in order to act. A table, a fenced block, a drawing and the \`[queue]\` cost nothing, so anything with parallel structure or a flow through it belongs in one of those rather than in prose."
exit 0
