#!/usr/bin/env bash
# Generated by ./build. Edit the sources at the repository root instead.

# Some clients never carry the session start hook's output into the session.
# The rules arrive on the first prompt instead, once.
input="$(cat)"

session_id="$(printf '%s' "$input" \
  | sed -n 's/.*"session_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"
[ -n "$session_id" ] || exit 0

. "$(dirname "$0")/hook-settings-lib.sh"
. "$(dirname "$0")/hook-say-lib.sh"

[ -f "$UNSOLICITED_TEXT_STATE/printed/$session_id" ] && exit 0

printf '{"hook_event_name":"UserPromptSubmit","session_id":"%s"}' "$session_id" \
  | UNSOLICITED_TEXT_PLAIN=1 "$(dirname "$0")/load-rules.sh" \
  | hook_say UserPromptSubmit
exit 0
