#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# A plugin that has to move something an older version left behind ships
# hooks/migrations.sh. It runs once per version, before anything reads state.
apply_migrations() {
  local applied="" installed marker="$PLUGIN_STATE/applied-version"

  # The common case is a marker written after the manifest it was read from.
  # Nothing has changed, so nothing is read.
  [ -f "$marker" ] && [ "$marker" -nt "$PLUGIN_ROOT/plugin.json" ] && return 0

  [ -f "$marker" ] && read -r applied < "$marker"
  installed="$(installed_version)" || return 0
  [ "$applied" = "$installed" ] && return 0

  [ -f "$PLUGIN_LIB/migrations.sh" ] && . "$PLUGIN_LIB/migrations.sh"

  mkdir -p "$PLUGIN_STATE" 2>/dev/null || return 0
  printf '%s\n' "$installed" > "$marker" 2>/dev/null
  return 0
}
