#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Clients differ in what they read from a hook. Every one of them reads this
# shape, and some read nothing else, so a hook that speaks says it this way.
#
# One function to a file, in say/.

. "${BASH_SOURCE[0]%/*}/payload.sh"
. "${BASH_SOURCE[0]%/*}/settings.sh"
. "${BASH_SOURCE[0]%/*}/say/hook_event_of.sh"
. "${BASH_SOURCE[0]%/*}/say/hook_escaped.sh"
. "${BASH_SOURCE[0]%/*}/say/hook_plain.sh"
. "${BASH_SOURCE[0]%/*}/say/hook_say.sh"
. "${BASH_SOURCE[0]%/*}/say/hook_say_aloud.sh"
