#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# The tool call a hook was handed, read the same way whichever client sent it.
# A hook on a tool event reads entries with tool_entries and never the client's
# own payload, so it names no client's tools.
#
# tool/tool_entries_read.sh is written by the build, and holds only the reading
# code for the client that distribution serves.
#
# One function to a file, in tool/.

. "${BASH_SOURCE[0]%/*}/payload.sh"
. "${BASH_SOURCE[0]%/*}/settings.sh"
. "${BASH_SOURCE[0]%/*}/tool/tool_command_matches.sh"
. "${BASH_SOURCE[0]%/*}/tool/tool_wanted.sh"
. "${BASH_SOURCE[0]%/*}/tool/tool_entries.sh"
if [ -f "${BASH_SOURCE[0]%/*}/tool/tool_entries_read.sh" ]; then
  . "${BASH_SOURCE[0]%/*}/tool/tool_entries_read.sh"
fi
