#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# A note for the next prompt, written at the end of a turn because nothing a
# stop hook prints reaches the session.
stop_note_record() {
  local session_id="$1" note="$2" notes_file
  [ -n "$session_id" ] && [ -n "$note" ] || return 0
  plugin_notes
  notes_file="$PLUGIN_NOTES/$session_id.stop-notes"
  mkdir -p "$PLUGIN_NOTES"
  printf '%s\n' "$note" >> "$notes_file"
}
