#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Every note this session is holding, read once and gone, so nothing is
# replayed on the prompt after the one that carried it.
stop_note_take() {
  local session_id="$1" notes_file
  plugin_notes
  notes_file="$PLUGIN_NOTES/$session_id.stop-notes"
  [ -f "$notes_file" ] || return 0
  cat "$notes_file"
  rm -f "$notes_file"
}
