#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# The payload read without jq, for a harness on a machine that has none.
#
# It walks the JSON rather than matching it, so a key nested inside another
# object is not mistaken for the one asked for, and a value stops at the quote
# that closes it rather than at the first one inside it.
payload_scanned() {
  printf '%s' "$1" | awk -v want="$2" '
    function unescaped(s,   out, i, c, n) {
      out = ""
      for (i = 1; i <= length(s); i++) {
        c = substr(s, i, 1)
        if (c != "\\") { out = out c; continue }
        i++
        n = substr(s, i, 1)
        if (n == "n") out = out "\n"
        else if (n == "t") out = out "\t"
        else if (n == "r") out = out "\r"
        else if (n == "u") { out = out "\\u" substr(s, i + 1, 4); i += 4 }
        else out = out n
      }
      return out
    }

    # One string, from the opening quote at i. Leaves i on the closing quote.
    function string_at(s, i,   out, c) {
      out = ""
      for (i = i + 1; i <= length(s); i++) {
        c = substr(s, i, 1)
        if (c == "\\") { out = out c substr(s, i + 1, 1); i++; continue }
        if (c == "\"") break
        out = out c
      }
      ends = i
      return out
    }

    {
      payload = payload $0
    }

    END {
      depth = 0
      i = 1
      while (i <= length(payload)) {
        c = substr(payload, i, 1)

        if (c == "\"") {
          token = string_at(payload, i)
          i = ends + 1
          # A key is a string at the top level with a colon after it.
          while (i <= length(payload) && substr(payload, i, 1) ~ /[ \t\n]/) i++
          if (depth == 1 && substr(payload, i, 1) == ":") {
            i++
            while (i <= length(payload) && substr(payload, i, 1) ~ /[ \t\n]/) i++
            if (token == want) {
              if (substr(payload, i, 1) == "\"") {
                printf "%s", unescaped(string_at(payload, i))
                exit 0
              }
              # true, false, null and numbers carry no quotes.
              value = ""
              while (i <= length(payload) && substr(payload, i, 1) ~ /[A-Za-z0-9.eE+-]/) {
                value = value substr(payload, i, 1)
                i++
              }
              # null is a key that was not really sent, which is how jq reads it.
              if (value == "null" || value == "") exit 1
              printf "%s", value
              exit 0
            }
          }
          continue
        }

        if (c == "{" || c == "[") depth++
        else if (c == "}" || c == "]") depth--
        i++
      }
      exit 1
    }
  '
}
