#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# The tool call Codex handed a hook, as the entries every plugin reads. Codex
# makes every file change through apply_patch, and one patch can add, change,
# delete and move several files at once, so one call can be several entries,
# one JSON object to a line.
tool_entries_read() {
  jq --compact-output '
    def blank: {kind: "", tool: "", file: "", command: "", added: "", removed: "",
                pattern: "", url: "", query: "", prompt: ""};
    def finished: if . == null then [] else [.] end;
    .tool_name as $tool | (.tool_input // {}) as $input
    | if $tool == "Bash" then blank + {kind: "bash", tool: $tool, command: ($input.command // "")}
      elif $tool == "apply_patch" then
        ($input.command // $input.patch // $input.input // "" | split("\n"))
        | reduce .[] as $line ({done: [], open: null};
            if ($line | startswith("*** Add File: ")) then
              .done += (.open | finished) | .open = {kind: "write", file: ($line | ltrimstr("*** Add File: ")), added: [], removed: [], hunks: 0}
            elif ($line | startswith("*** Update File: ")) then
              .done += (.open | finished) | .open = {kind: "edit", file: ($line | ltrimstr("*** Update File: ")), added: [], removed: [], hunks: 0}
            elif ($line | startswith("*** Delete File: ")) then
              .done += (.open | finished) + [{kind: "delete", file: ($line | ltrimstr("*** Delete File: ")), added: [], removed: [], hunks: 0}]
              | .open = null
            elif ($line | startswith("*** Move to: ")) and .open != null then
              .done += [{kind: "move", file: .open.file, pattern: ($line | ltrimstr("*** Move to: ")), added: [], removed: [], hunks: 0}]
            elif ($line | startswith("*** ")) then .
            elif .open == null then .
            elif ($line | startswith("@@")) then .open.hunks += 1
            elif ($line | startswith("+")) then .open.added += [$line[1:]]
            elif ($line | startswith("-")) then .open.removed += [$line[1:]]
            else . end)
        | (.done + (.open | finished))[]
        | (if .kind == "edit" and .hunks > 1 then .kind = "multi_edit" else . end)
        | blank + del(.hunks) + {tool: $tool, added: (.added | join("\n")), removed: (.removed | join("\n"))}
      elif ($tool // "" | test("^web\\.?run$")) then
        if $input.open then blank + {kind: "web_fetch", tool: $tool, url: ($input.open | tostring)}
        else blank + {kind: "web_search", tool: $tool, query: ($input.search // $input.query // "" | tostring)} end
      elif ($tool // "" | test("spawn_agent$")) then blank + {kind: "agent", tool: $tool, prompt: ($input.message // "")}
      elif ($tool // "" | startswith("mcp__")) then blank + {kind: "mcp", tool: $tool, input: $input}
      else blank + {kind: "other", tool: $tool, input: $input} end
  ' <<< "$1" 2>/dev/null
}
