#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# A note one hook writes and another reads back on the next prompt. The
# directory is this plugin's own, so two plugins installed together do not
# drain each other's notes.
#
# One function to a file, in notes/.

. "${BASH_SOURCE[0]%/*}/state.sh"

apply_migrations

. "${BASH_SOURCE[0]%/*}/notes/plugin_notes.sh"
. "${BASH_SOURCE[0]%/*}/notes/stop_note_record.sh"
. "${BASH_SOURCE[0]%/*}/notes/stop_note_take.sh"
