#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# The plugin these libraries were built for. Nothing else here names it.

PLUGIN_NAME='unsolicited-text'
PLUGIN_PREFIX='UNSOLICITED_TEXT'
PLUGIN_DISPLAY_NAME='unsolicited-text'

plugin_setting_default() {
  case "$1" in
    STOP_NOTE_DIRECTORY) printf '%s' '{state}/notes' ;;
    UPDATE_CHECK) printf '%s' 'on' ;;
    UPDATE_CHECK_DAYS) printf '%s' '1' ;;
    VERSION_SOURCE) printf '%s' 'https://raw.githubusercontent.com/justinkek/unsolicited-text/main/package.json' ;;
    PROSE_LINE_CEILING) printf '%s' '8' ;;
    PROSE_WORD_CEILING) printf '%s' '120' ;;
    QUEUE_MAX_VISIBLE_ITEMS) printf '%s' '' ;;
    QUEUE_EMOJI) printf '%s' 'off' ;;
    BREADCRUMB) printf '%s' 'off' ;;
    QUEUE_TREE) printf '%s' 'on-switch-only' ;;
  esac
}

plugin_setting_kind() {
  case "$1" in
    STOP_NOTE_DIRECTORY) printf '%s' 'text' ;;
    UPDATE_CHECK) printf '%s' 'switch' ;;
    UPDATE_CHECK_DAYS) printf '%s' 'count' ;;
    VERSION_SOURCE) printf '%s' 'text' ;;
    PROSE_LINE_CEILING) printf '%s' 'count' ;;
    PROSE_WORD_CEILING) printf '%s' 'count' ;;
    QUEUE_MAX_VISIBLE_ITEMS) printf '%s' 'count' ;;
    QUEUE_EMOJI) printf '%s' 'switch' ;;
    BREADCRUMB) printf '%s' 'switch' ;;
    QUEUE_TREE) printf '%s' 'choice' ;;
  esac
}

plugin_setting_values() {
  case "$1" in
    QUEUE_TREE) printf '%s' 'always-on on-switch-only off' ;;
  esac
}

plugin_session_start_hooks() {
  printf '%s\n' 'load-rules.sh'
}
