#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Text on standard input, printed for the event named in $1 and shown to the
# user as well. The context reaches the agent either way.
hook_say_aloud() {
  local event="$1" said
  if hook_plain || [ -z "$event" ]; then cat; return 0; fi
  said="$(hook_escaped)"
  [ -n "$said" ] || return 0
  printf '{"systemMessage":"%s","hookSpecificOutput":{"hookEventName":"%s","additionalContext":"%s"}}\n' \
    "$said" "$event" "$said"
}
