#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Whether a mark is there. The name is a path, so a marker per session goes
# under a directory named for what it records.
plugin_marked() { [ -f "$PLUGIN_STATE/$1" ]; }
