#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Leaves the mark, and says whether it was already there.
plugin_mark_once() {
  plugin_marked "$1" && return 0
  plugin_mark "$1"
  return 1
}
