#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Whether a command matches a pattern such as `git *`, checked the way Claude
# Code checks `Bash(git *)`: each subcommand on its own, including the ones
# inside $() and backticks, with leading assignments stripped. A subcommand
# whose name is a variable cannot be known, so it matches.
tool_command_matches() {
  local pattern="$1" command="$2" part word
  while IFS= read -r part; do
    part="${part#"${part%%[![:space:]]*}"}"
    part="${part%"${part##*[![:space:]]}"}"
    while [[ "$part" =~ ^[A-Za-z_][A-Za-z0-9_]*=[^[:space:]]*[[:space:]]+(.*)$ ]]; do
      part="${BASH_REMATCH[1]}"
    done
    [ -n "$part" ] || continue
    word="${part%%[[:space:]]*}"
    case "$word" in
      '$'*) return 0 ;;
    esac
    # Unquoted on purpose: the pattern is a glob.
    # shellcheck disable=SC2053
    [[ "$part" == $pattern ]] && return 0
  done < <(printf '%s\n' "$command" \
    | awk '{ gsub(/\$\(|`|\)|&&|\|\||[;|&]/, "\n"); print }')
  return 1
}
