#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# The tool call a Claude client handed a hook, as the entries every plugin
# reads. Claude Code, Cowork and ZCode name their tools this way, and the Pi
# extension hands its tool calls over under these names too. One call is one
# entry, one JSON object to a line.
tool_entries_read() {
  jq --compact-output '
    .tool_name as $tool | (.tool_input // {}) as $input
    | if $tool == "Bash" or $tool == "mcp__remote-devices__device_bash" then {kind: "bash", command: $input.command}
      elif $tool == "PowerShell" then {kind: "powershell", command: $input.command}
      elif $tool == "Write" then {kind: "write", file: $input.file_path, added: $input.content}
      elif $tool == "Edit" then {kind: "edit", file: $input.file_path, added: $input.new_string, removed: $input.old_string}
      elif $tool == "MultiEdit" then {kind: "multi_edit", file: $input.file_path,
        added: ([$input.edits[]?.new_string] | join("\n")), removed: ([$input.edits[]?.old_string] | join("\n"))}
      elif $tool == "NotebookEdit" then {kind: "notebook_edit", file: $input.notebook_path, added: $input.new_source}
      elif $tool == "Read" then {kind: "read", file: $input.file_path}
      elif $tool == "Grep" then {kind: "grep", pattern: $input.pattern, file: $input.path}
      elif $tool == "Glob" then {kind: "glob", pattern: $input.pattern, file: $input.path}
      elif $tool == "LS" then {kind: "list", pattern: $input.path, file: $input.path}
      elif $tool == "WebFetch" then {kind: "web_fetch", url: $input.url}
      elif $tool == "WebSearch" then {kind: "web_search", query: $input.query}
      elif $tool == "Agent" or $tool == "Task" then {kind: "agent", prompt: $input.prompt}
      elif ($tool // "" | startswith("mcp__")) then {kind: "mcp", input: $input}
      else {kind: "other", input: $input} end
    | {kind, tool: $tool, file: "", command: "", added: "", removed: "", pattern: "", url: "", query: "", prompt: ""}
      + with_entries(select(.value != null))
  ' <<< "$1" 2>/dev/null
}
