#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Writes one setting into the settings file and leaves everything else in it
# alone, comments and order included.
#
#   bash set-setting.sh <key> <value>
#
# The key is written the way the settings skill's table shows it, with or
# without the plugin's prefix. A key this plugin does not have, or a value the
# setting cannot take, is refused and nothing is written.

. "$(dirname "$0")/hooks/lib/settings.sh"

[ "$#" = "2" ] || {
  printf 'usage: set-setting.sh <key> <value>\n' >&2
  exit 2
}

bare="${1#"${PLUGIN_PREFIX}_"}"
named="${PLUGIN_PREFIX}_$bare"
value="$2"

[ -n "$(plugin_setting_kind "$bare")" ] || {
  printf '%s has no setting called %s.\n' "$PLUGIN_NAME" "$named" >&2
  exit 1
}

plugin_setting_holds "$bare" "$value" || {
  printf '%s does not take "%s".\n' "$named" "$value" >&2
  case "$(plugin_setting_kind "$bare")" in
    count) printf 'It takes a whole number.\n' >&2 ;;
    switch) printf 'It takes on or off.\n' >&2 ;;
    choice) printf 'It takes one of: %s\n' "$(plugin_setting_values "$bare")" >&2 ;;
  esac
  exit 1
}

mkdir -p "$(dirname "$PLUGIN_SETTINGS")" || {
  printf 'cannot write %s\n' "$PLUGIN_SETTINGS" >&2
  exit 1
}

[ -f "$PLUGIN_SETTINGS" ] || : > "$PLUGIN_SETTINGS"

# The new value goes where the old one was, so a file a person has arranged
# stays arranged. A key assigned more than once is left assigned once.
awk -v named="$named" -v value="$value" '
  $0 ~ "^[[:space:]]*" named "[[:space:]]*=" {
    if (!written) { print named " = " value; written = 1 }
    next
  }
  { print }
  END { if (!written) print named " = " value }
' "$PLUGIN_SETTINGS" > "$PLUGIN_SETTINGS.new" && mv "$PLUGIN_SETTINGS.new" "$PLUGIN_SETTINGS"

printf '%s = %s\n' "$named" "$value"
printf 'written to %s\n' "$PLUGIN_SETTINGS"
