#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# What the settings file says for one key, or nothing. The last assignment of a
# key is the one that counts.
settings_file_value() {
  local key="$1" value
  [ -f "$PLUGIN_SETTINGS" ] || return 1
  value="$(sed -n "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*//p" "$PLUGIN_SETTINGS" \
    | sed 's/[[:space:]]*$//' | tail -n 1)"
  [ -n "$value" ] || return 1
  printf '%s' "$value"
}
