#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# Whether a switch is on. Anything a switch cannot take read as the default
# before it got here.
setting_on() { [ "$(setting_value "$1")" = "on" ]; }
