#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# The project a hook is working in, as the payload names it. A directory that
# is not there leaves the one the hook was run in.
# One function to a file means no file can see its own variable being read, so
# it looks unused here. settings/ reads it.
# shellcheck disable=SC2034
settings_from_project() {
  [ -n "$1" ] && [ -d "$1" ] || return 0
  PLUGIN_PROJECT="$1"
}
